services:
  db:
    image: postgres:13.21
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE: postgres
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "8000:8000"

#  jinja-app:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    restart: always
#    depends_on:
#      - backend
#    ports:
#      - "8001:8001"

volumes:
  db_data:
